name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Verify dependencies
        run: |
          go mod download
          go mod verify

      - name: Check go fix suggestions
        run: go fix -diff ./...

      - name: Run linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

      - name: Run tests
        run: go test -v -race ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --snapshot --clean
